use_frameworks!
platform :ios, '8.0'

target 'RxJoystickView_Example' do
  pod 'RxJoystickView', :path => '../'

  target 'RxJoystickView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
