use_frameworks!

target 'RxJoystickView_Example' do
  pod 'RxJoystickView', :path => '../'

  target 'RxJoystickView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
